overblog_graphql:
    definitions:
        schema:
            query: Query
            mutation: ~
        mappings:
            types:
                -   type: yaml
                    dir: "%kernel.project_dir%/config/graphql/types"
                    suffix: null
    services:
        promise_adapter: "webonyx_graphql.sync_promise_adapter"

overblog_dataloader:
    defaults:
        promise_adapter: "overblog_dataloader.webonyx_graphql_sync_promise_adapter"
    loaders:
        salaries:
            alias: "user_salaries_loader"
            batch_load_fn: "@App\\GraphQL\\Loader\\SalariesLoader:resolveByUser"
        equipment:
            alias: "user_equipment_loader"
            batch_load_fn: "@App\\GraphQL\\Loader\\EquipmentLoader:resolveByUser"
        user_invoices:
            alias: "user_invoices_loader"
            batch_load_fn: "@App\\GraphQL\\Loader\\InvoicesLoader:resolveByUser"
        client_invoices:
            alias: "client_invoices_loader"
            batch_load_fn: "@App\\GraphQL\\Loader\\InvoicesLoader:resolveByClient"
        clients:
            alias: "user_clients_loader"
            batch_load_fn: "@App\\GraphQL\\Loader\\ClientsLoader:resolveByUser"
        client:
            alias: 'client_loader'
            batch_load_fn: '@App\\GraphQL\\Loader\\ClientsLoader:resolveById'
        user:
            alias: "user_loader"
            batch_load_fn: "@App\\GraphQL\\Loader\\UsersLoader:resolveById"


