services:
  app:
    environment:
      APP_ENV: ${APP_ENV:-dev}
      APP_SECRET: ${APP_SECRET:-changeme}

  database:
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
      MYSQL_DATABASE: ${DATABASE_NAME:-ldbiro}
      MYSQL_USER: ${DATABASE_USER:-sasa}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD:-sasatest123}

  phpmyadmin:
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
      PMA_USER: ${DATABASE_USER:-sasa}
      PMA_PASSWORD: ${DATABASE_PASSWORD:-sasatest123}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}

