Invoice:
    type: object
    config:
        description: "An invoice created and sent to a client."
        fields:
            id:
                type: "Int!"
            amount:
                type: "Int!"
            paymentStatus:
                type: "PaymentStatus!"
            periodStart:
                type: "String!"
            periodEnd:
                type: "String!"
            issuer:
                type: "User!"
                resolve: "@=service('user_loader').load(value.getIssuer().getId())"
            client:
                type: "Client!"
                resolve: "@=service('client_loader').load(value.getClient().getId())"

